apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsback:1.0.0-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsback:1.0.0-3
  template:
    metadata:
      labels:
        app: devopsback:1.0.0-3
    spec:
      containers:
      - name: devopsback:1.0.0-3
        image: truthaniket/devopsback:1.0.0-3
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: service-html-back
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 5000
  selector:
    app: devopsback:1.0.0-3
