apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsback
  template:
    metadata:
      labels:
        app: devopsback
    spec:
      containers:
      - name: devopsback
        image: truthaniket/devopsback:1.0.0-10
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: service-html
spec:
  type: LoadBalancer
  ports:
  - port: 8082
    targetPort: 5000
  selector:
    app: devopsback
