apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops
        image: truthaniket/devopsfront:1.0.0-9
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: service-html
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    targetPort: 3000
  selector:
    app: devops
